### PR TITLE
Updated population

### PR DESCRIPTION
**Pull request by Arsh1a**
All of countries population has been updated based on 2019 United Nation statics and World Bank and minified.

Fix for #200

### CODE REVIEW

**Comment by amatosg** [comment]
please correct me if I'm wrong,  but the only change I see is India?

**Comment by Arsh1a** [comment]
No all of them have been updated based on 2019 statics. Only Antarctica and some little island that is inhabited are the same.

**Comment by amatosg** [comment]
that's weird, I made a side by side comparison and only saw India. It might be a mistake on my side

**Comment by Arsh1a** [comment]
I'm comparing most of them with the API again. All of them are updated. 
Are you sure you are looking at [this](https://github.com/apilayer/restcountries/pull/204/commits/f1d367c40b69ebdb23e58f4d081a5fe0afc0c281) and [this](https://github.com/apilayer/restcountries/pull/204/commits/034ba32670cd52ca2f9c4ee37d9e6dff64087a89) ?

**Comment by kg-currenxie** [comment]
Updates on this? Would like the new population figures :) <3

**Comment by amatosg** [comment]
@Arsh1a because of how the files have been uploaded, I cannot see the diffs. You might want to submit your changes [here](https://gitlab.com/amatos/rest-countries/-/issues) so I can implement it on restcountries.com

**Comment by kg-currenxie** [comment]
http://www.jsondiff.com/ ? :)

**Comment by Frexuz** [comment]
Any change of getting this merged soon? :)

**Comment by ePascalC** [comment]
#255 merged with 2020 data

**Pull request closed without merging**
