### PR TITLE
Correct spelling

### PR DESCRIPTION
**Pull request by Leon99**
See https://www.iso.org/obp/ui#iso:code:3166:UA, https://www.google.com/maps/place/Kyiv,+Ukraine,+02000, https://github.com/mledoze/countries/pull/215

### CODE REVIEW

**Comment by Leon99** [comment]
> Would you please propose this at https://en.wikipedia.org/wiki/Kiev too.
Propose what exactly? The article states that the internationally accepted spelling is Kyiv.

**Comment by Amn3s1a2018** [comment]
It is in the article, yes, but the article itself does not use that spelling instead. The title should be Kyiv and the redirection goes the wrong way too.

**Comment by Leon99** [comment]
@Amn3s1a2018 changing redirection was proposed many times by many people. There is even an [official letter from Kyiv City State Administration ](https://en.wikipedia.org/wiki/Kiev#/media/File:Kyiv_City_State_Administration_Letter_to_WMF.jpg) asking for spelling correction. No objective reason was given as to the reason, but it was declined every time. Guess why? [Hint](https://en.wikipedia.org/wiki/Hybrid_warfare)

**Comment by Amn3s1a2018** [comment]
Now i read the talk pages about it (omg i dont want to be wiki editor), and i almost got their counterpoint too. Anyway, i merged this (with few other PR) to my version, hope some ppl from @apilayer will take care the project soon and do the same.

**Comment by andrewdunai** [comment]
@Amn3s1a2018 Can this get some attention now? The wiki page now redirects to the correct spelling which is "Kyiv".

**Comment by Amn3s1a2018** [comment]
No commit or merge since one year and half. You should probably switch to using another project like [mledoze/countries](/mledoze/countries) witch is alive... (And refers Київ as Kyiv btw)

**Comment by amatosg** [comment]
restcountries.com is also available and compatible with this repository :)

**Comment by amatosg** [comment]
If you want to run it locally, you can use the docker image:
`docker pull registry.gitlab.com/amatos/rest-countries:latest`
and run it with
`docker run -d -p 8080:8080 registry.gitlab.com/amatos/rest-countries:latest`

**Comment by ePascalC** [comment]
Updated to Kyiv. Thanks.

**Pull request closed without merging**
