### PR TITLE
Update `countriesV2.json` to remove unnecessary empty  currency from Zimbabwe

### PR DESCRIPTION
**Pull request by techeverri**
```diff
{
  "name": "Zimbabwe",
  "currencies": [
    {
      "code": "BWP",
      "name": "Botswana pula",
      "symbol": "P"
    },
    {
      "code": "GBP",
      "name": "British pound",
      "symbol": "£"
    },
    {
      "code": "CNY",
      "name": "Chinese yuan",
      "symbol": "¥"
    },
    {
      "code": "EUR",
      "name": "Euro",
      "symbol": "€"
    },
    {
      "code": "INR",
      "name": "Indian rupee",
      "symbol": "₹"
    },
    {
      "code": "JPY",
      "name": "Japanese yen",
      "symbol": "¥"
    },
    {
      "code": "ZAR",
      "name": "South African rand",
      "symbol": "Rs"
    },
    {
      "code": "USD",
      "name": "United States dollar",
      "symbol": "$"
+   }
-   },
-   {
-    "code": "(none)",
-     "name": null,
-     "symbol": null
-   }
  ]
}
```

### CODE REVIEW

**Comment by techeverri** [comment]
What was the problem with this pull request?
_Why was it closes in favor of #258?_

**Comment by ePascalC** [comment]
@techeverri there was no issue with your PR at all, I hope I did not offend you. As most of the PRs need a rebase and that will take too much time for me, I'm just combining/executing all changes in a different way. I just got access here some time ago and I try to implement as fast as possible all the pending changes requested over the last years:
https://github.com/apilayer/restcountries/issues?q=is%3Aclosed+sort%3Aupdated-desc+

**Comment by techeverri** [comment]
No offense taken 👍
_I was genuinely curious and wanted to know if there was any mistake that made the pull request unmergeable_
Also, it's really cool to appear in repos that one contributes to.

**Comment by techeverri** [comment]
This feature of git `Co-authored-by` might be helpful if you want to create new pull requests to merge them faster buy keeping the original authorship in the history of the repo @ePascalC 

- https://github.blog/2018-01-29-commit-together-with-co-authors/

**Pull request closed without merging**
